#Set Up Parameters
run_infill: True
run_land_use: True 

#Mandatory Parameters
#--str
lookups_sheet_name: "Lookups"
#--Read file paths 
dlog_input_file: C:\Users\UKKXF022\Documents\DLOG\DLog_data\DLog21_v8_issued_v1.xlsx
#--Write file paths 
output_folder: C:\Users\UKKXF022\Documents\DLOG\DLIT_outputs
proposed_luc_split_path: C:\Users\UKKXF022\Documents\DLOG\DLIT_outputs\proposed_luc_split_path.csv
existing_luc_split_path: C:\Users\UKKXF022\Documents\DLOG\DLIT_outputs\existing_luc_split_path.csv

infill:
  combined_sheet_name: "2021 Combined"
  residential_sheet_name: "2021 Residential"
  employment_sheet_name: "2021 Employment"
  mixed_sheet_name: "2021 Mixed"
  #--Read file paths 
  dlog_column_names_path: inputs\DLog_column_names.csv
  combined_column_names_path: inputs\combined_column_names.csv
  residential_column_names_path: inputs\residential_column_names.csv
  employment_column_names_path: inputs\employment_column_names.csv
  mixed_column_names_path: inputs\mixed_column_names.csv
  ignore_columns_path: inputs\drop_columns.csv
  valid_luc_path: inputs\valid_luc.csv
  out_of_date_luc_path: inputs\out_of_date_luc.csv
  incomplete_luc_path: inputs\incomplete_luc.csv
  known_invalid_luc_path: inputs\known_invalid_luc.csv
  regions_shapefiles_path: inputs\LPA_shapefiles\Local_Planning_Authorities_(April_2020)_UK_BFE.shp
  #--write file paths  
  user_input_path: C:\Users\UKKXF022\Documents\DLOG\DLIT_outputs\user_input.xlsx

land_use:
  land_use_input: C:\Users\UKKXF022\Documents\DLOG\DLIT_outputs\03_post_fixes\post_fix_data.xlsx
  msoa_shapefile_path:  C:\Users\UKKXF022\Documents\DLOG\MSOA_shapefile\uk_ew_msoa_s_iz_north_flags.shp
  msoa_dwelling_pop_path: C:\Users\UKKXF022\Documents\DLOG\big_inputs\gb_msoa_agg_prt_2018_hh_pop.csv
  msoa_traveller_type_path: C:\Users\UKKXF022\Documents\DLOG\big_inputs\land_use_2018_pop.csv
  msoa_jobs_path: C:\Users\UKKXF022\Documents\DLOG\big_inputs\land_use_2018_emp.csv
  employment_density_matrix_path: inputs\emp_density_matrix.csv
  luc_sic_conversion_path: inputs\luc_sic_conversion.csv




