#Mandatory Parameters

#--Read file paths
jobs_input_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\jobs.csv
population_input_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\population.csv
#--Write file paths
output_folder: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_outputs
proposed_luc_split_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\proposed_luc_split_path.csv
existing_luc_split_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\existing_luc_split_path.csv
msoa_dwelling_pop_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\gb_msoa_agg_prt_2018_hh_pop.csv
msoa_traveller_type_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\land_use_2018_pop.csv
msoa_to_lad_conversion_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\msoa_to_lad_2020_correspondence.csv
msoa_jobs_path: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_inputs\land_use_2018_emp.csv
employment_density_matrix_path: inputs\emp_density_matrix.csv
luc_sic_conversion_path: inputs\luc_sic_conversion.csv


