#Set Up Parameters
run_infill: True
run_land_use: False

#Mandatory Parameters
#--str
lookups_sheet_name: "Lookups"
#--Read file paths
dlog_input_file: Y:\D_I-Log\D-Log21\D-Log21_v8\DLog21_v8_issued_v1.xlsx
#--Write file paths
output_folder: E:\dlit\DLIT_output
proposed_luc_split_path: E:\dlit\DLIT_output\luc_splits\proposed_luc_split_path.csv
existing_luc_split_path: E:\dlit\DLIT_output\luc_splits\existing_luc_split_path.csv

infill:
  user_infill: False
  combined_sheet_name: "2021 Combined"
  residential_sheet_name: "2021 Residential"
  employment_sheet_name: "2021 Employment"
  mixed_sheet_name: "2021 Mixed"
  #--Read file paths
  dlog_column_names_path: inputs\DLog_column_names.csv
  valid_luc_path: inputs\valid_luc.csv
  out_of_date_luc_path: inputs\out_of_date_luc.csv
  incomplete_luc_path: inputs\incomplete_luc.csv
  known_invalid_luc_path: inputs\known_invalid_luc.csv
  regions_shapefiles_path: inputs\LPA_shapefiles\Local_Planning_Authorities_(April_2020)_UK_BFE.shp
  #--write file paths
  user_input_path: E:\dlit\DLIT_output\luc_splits\user_input.xlsx
  gfa_infill_method: regression
