#Set Up Parameters
run_infill: False
run_land_use: True

#Mandatory Parameters
#--str
lookups_sheet_name: "Lookups"
#--Read file paths
dlog_input_file: Y:\D_I-Log\D-Log21\D-Log21_v8\DLog21_v8_issued_v1.xlsx
#--Write file paths
output_folder: E:\dlit\DLIT_output
proposed_luc_split_path: E:\dlit\DLIT_output\luc_splits\proposed_luc_split_path.csv
existing_luc_split_path: E:\dlit\DLIT_output\luc_splits\existing_luc_split_path.csv

infill:
  user_infill: False
  combined_sheet_name: "2021 Combined"
  residential_sheet_name: "2021 Residential"
  employment_sheet_name: "2021 Employment"
  mixed_sheet_name: "2021 Mixed"
  #--Read file paths
  dlog_column_names_path: inputs\DLog_column_names.csv
  valid_luc_path: inputs\valid_luc.csv
  out_of_date_luc_path: inputs\out_of_date_luc.csv
  incomplete_luc_path: inputs\incomplete_luc.csv
  known_invalid_luc_path: inputs\known_invalid_luc.csv
  regions_shapefiles_path: inputs\LPA_shapefiles\Local_Planning_Authorities_(April_2020)_UK_BFE.shp
  #--write file paths
  user_input_path: E:\dlit\DLIT_output\luc_splits\user_input.xlsx
  gfa_infill_method: regression

land_use:
  land_use_input: E:\dlit\DLIT_output\03_post_fixes\post_fix_data.xlsx
  msoa_shapefile_path: I:\Data\D-Log\DLIT\Inputs\MSOA_shapefile\uk_ew_msoa_s_iz_north_flags.shp
  msoa_dwelling_pop_path: I:\Data\D-Log\DLIT\Inputs\gb_msoa_agg_prt_2018_hh_pop.csv
  msoa_traveller_type_path: I:\Data\D-Log\DLIT\Inputs\land_use_2018_pop.csv
  msoa_jobs_path: I:\Data\D-Log\DLIT\Inputs\land_use_2018_emp.csv
  employment_density_matrix_path: inputs\emp_densities\emp_density_matrix_min.csv
  luc_sic_conversion_path: inputs\luc_sic_conversion.csv
  demolition_dampener: 1
  summary_data:
    summary_zone_name: lad_2020
    lookup_file: I:\Data\D-Log\DLIT\Inputs\msoa_to_lad_2020_lookup.csv
    shapefile: Y:\Data Strategy\GIS Shapefiles\Local_Authority_Districts_(December_2020)_UK_BFC\Local_Authority_Districts_(December_2020)_UK_BGC-simple_100.shp
    shapefile_id_column: LAD20CD
